# Generated by Django 3.2.12 on 2022-07-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='config',
        ),
    ]
